<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitd624d4d2f765dae2e5634ba9ea24f462
{
    public static $prefixLengthsPsr4 = array (
        'P' => 
        array (
            'PHPMailer\\PHPMailer\\' => 20,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'PHPMailer\\PHPMailer\\' => 
        array (
            0 => __DIR__ . '/..' . '/phpmailer/phpmailer/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitd624d4d2f765dae2e5634ba9ea24f462::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitd624d4d2f765dae2e5634ba9ea24f462::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInitd624d4d2f765dae2e5634ba9ea24f462::$classMap;

        }, null, ClassLoader::class);
    }
}
